name: Lighthouse CI
on:
  push:
    branches:
      - main

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g @lhci/cli
      - name: Run Lighthouse collect
        run: lhci collect
      - name: Run Lighthouse assert
        run: lhci assert
